### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by clayellis** [emarashliev/swift-nio-http2-client#3]
Hey @emarashliev 👋 Just out of curiosity, would you be open to renaming this library? I'm not asking on behalf of the Swift Server Work Group, just as myself, but I noticed that they're trying to find a good name for their new Swift NIO HTTP Client and don't want to step on your toes. https://forums.swift.org/t/feedback-nio-based-http-client/26149/2

If you're not up for that, no worries, seriously. I just thought I'd ask since none of them have, nor do I think they would.

**Comment by emarashliev** [comment]
Hey @clayellis of course I can do this. I just wrote in the forums discussion that you linked. We can continue if there's something else in the forums. Thank you so much  for letting me know. 🙂

**Comment by emarashliev** [comment]
@clayellis done ✅

**Comment by clayellis** [comment]
Thanks for being so flexible!

**Comment by emarashliev** [comment]
@clayellis sure, everything for the community! 😉

**Comment by emarashliev** [comment]
@clayellis sure, no worries. Everything for the community! 😉
